[project]
name = "external_approval_digital_sign"
authors = [
    { name = "Your Name", email = "your.email@example.com"}
]
description = "Plug and play Frappe app for external client approval and digital signature capture"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "frappe~=16.0.0",
    "pypika @ git+https://github.com/frappe/pypika@2c50e6142b2d61d2d243e466fdd5dc03b3d918f2",

]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"
